{% set name = "workalendar" %}
{% set version = "13.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 649c71791844590efe57f6568fab3520b66daff0a86e18a4c87e1e6cf77e7544

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python

  run:
    - lunardate
    - pycalverter
    - skyfield
    - skyfield-data
    - pyluach
    - python
    - python-dateutil
    - pytz
    - setuptools >=1.0
    - freezegun

test:
  imports:
    - workalendar
    - workalendar.africa
    - workalendar.america
    - workalendar.asia
    - workalendar.europe
    - workalendar.europe.scotland
    - workalendar.europe.scotland.mixins
    - workalendar.oceania
    - workalendar.tests
    - workalendar.usa

about:
  home: https://github.com/peopledoc/workalendar
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Worldwide holidays and working days helper and toolkit.

extra:
  recipe-maintainers:
    - Matt-BF
