{% set name = "workalendar" %}
{% set version = "5.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e40f7218deb1006f7eaff66172fa6380a74f1871ad2c549435a76d30255089d4

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    
  run:
    - ephem
    - lunardate
    - pycalverter
    - pyluach
    - python
    - python-dateutil
    - pytz
    - setuptools >=1.0

test:
  imports:
    - workalendar
    - workalendar.africa
    - workalendar.america
    - workalendar.asia
    - workalendar.europe
    - workalendar.europe.scotland
    - workalendar.europe.scotland.mixins
    - workalendar.oceania
    - workalendar.tests
    - workalendar.usa

about:
  home: https://github.com/peopledoc/workalendar
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Worldwide holidays and working days helper and toolkit.

extra:
  recipe-maintainers:
    - Matt-BF
